-- public."Personajes" definition

-- Drop table

-- DROP TABLE public."Personajes";

CREATE TABLE public."Personajes" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"Nivel" int4 NOT NULL,
	"FechaCreacion" timestamptz NOT NULL,
	"Gremio" text NULL,
	"Rasgos" jsonb NULL,
	CONSTRAINT "PK_Personajes" PRIMARY KEY ("Id")
);


-- public."__EFMigrationsHistory" definition

-- Drop table

-- DROP TABLE public."__EFMigrationsHistory";

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


-- public."Arqueros" definition

-- Drop table

-- DROP TABLE public."Arqueros";

CREATE TABLE public."Arqueros" (
	"Id" int4 NOT NULL,
	"Precision" float8 NOT NULL,
	"TieneMascota" bool NOT NULL,
	CONSTRAINT "PK_Arqueros" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Arqueros_Personajes_Id" FOREIGN KEY ("Id") REFERENCES public."Personajes"("Id") ON DELETE CASCADE
);


-- public."Clerigos" definition

-- Drop table

-- DROP TABLE public."Clerigos";

CREATE TABLE public."Clerigos" (
	"Id" int4 NOT NULL,
	"Deidad" text NOT NULL,
	"PuntosSanacion" int4 NOT NULL,
	CONSTRAINT "PK_Clerigos" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Clerigos_Personajes_Id" FOREIGN KEY ("Id") REFERENCES public."Personajes"("Id") ON DELETE CASCADE
);


-- public."Guerreros" definition

-- Drop table

-- DROP TABLE public."Guerreros";

CREATE TABLE public."Guerreros" (
	"Id" int4 NOT NULL,
	"ArmaPrincipal" text NOT NULL,
	"Furia" int4 NOT NULL,
	CONSTRAINT "PK_Guerreros" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Guerreros_Personajes_Id" FOREIGN KEY ("Id") REFERENCES public."Personajes"("Id") ON DELETE CASCADE
);


-- public."Magos" definition

-- Drop table

-- DROP TABLE public."Magos";

CREATE TABLE public."Magos" (
	"Id" int4 NOT NULL,
	"Mana" int4 NOT NULL,
	"ElementoPrincipal" text NOT NULL,
	CONSTRAINT "PK_Magos" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Magos_Personajes_Id" FOREIGN KEY ("Id") REFERENCES public."Personajes"("Id") ON DELETE CASCADE
);